/* Central Texas Now — content store.
   Legacy articles rebuilt from the site's historical high-equity URLs
   (sister cities = the Wikipedia-linked flagship), plus current feed. */
window.CTN_DATA = (function () {
  const SECTIONS = {
    news:      { slug: "news",      name: "News",            blurb: "What's happening across Waco, Temple, Killeen and the Bell County line." },
    crime:     { slug: "crime",     name: "Crime & Courts",  blurb: "Cases, trials and public safety from the courthouses of Central Texas." },
    weather:   { slug: "weather",   name: "Weather",         blurb: "Forecasts, alerts and the live regional radar." },
    sports:    { slug: "sports",    name: "Sports",          blurb: "Baylor, the high schools, and the teams that carry the region." },
    politics:  { slug: "politics",  name: "Politics",        blurb: "City halls, the county and the Capitol — and what it means at home." },
    community: { slug: "community", name: "Community",       blurb: "The people, places and small wonders of the heart of Texas." },
  };

  // Shorthand for image placeholder gradients (no external assets).
  const G = {
    army:   "linear-gradient(135deg,#2c3640,#5e4233 60%,#7a2230)",
    flag:   "linear-gradient(135deg,#7a2531,#a8122c)",
    silos:  "linear-gradient(135deg,#46563f,#8a8a55)",
    court:  "linear-gradient(135deg,#6f5436,#b78344)",
    hoops:  "linear-gradient(135deg,#3b3340,#665672)",
    radar:  "linear-gradient(135deg,#35404e,#5d6b7a)",
    lake:   "linear-gradient(135deg,#2f5d6b,#7fa6a0)",
    memorial:"linear-gradient(135deg,#23303c,#4a5b68)",
    cats:   "linear-gradient(135deg,#6a4a36,#c2884a)",
    road:   "linear-gradient(135deg,#3a3f45,#6b7178)",
    school: "linear-gradient(135deg,#52432f,#9a7b46)",
  };

  const ARTICLES = [
    /* ===== FLAGSHIP — the Wikipedia-linked URL (186 referring links) ===== */
    {
      id: "killeen-san-juan-sister-cities",
      section: "community",
      kicker: "Killeen",
      title: "Killeen and San Juan, Puerto Rico Are Now “Sister Cities”",
      dek: "A friendship agreement signed at City Hall ties the home of Fort Hood to Puerto Rico’s capital — a nod to the thousands of soldiers and families who connect the two.",
      hero: G.flag,
      heroCap: "Mayors of Killeen and San Juan exchange signed proclamations at Killeen City Hall.",
      author: "Dana Ruiz",
      role: "Staff Writer",
      date: "December 12, 2010",
      readMin: 4,
      tags: ["Killeen", "Fort Hood", "Puerto Rico", "City Council"],
      flagship: true,
      body: [
        { t: "p", x: "KILLEEN — The city that grew up alongside Fort Hood added an unlikely friend this week. In a ceremony at City Hall on Saturday, Killeen and San Juan, Puerto Rico, formally became “sister cities,” pledging cultural, educational and economic ties between the Central Texas community and the island’s 500-year-old capital." },
        { t: "p", x: "The agreement, signed by both mayors before a crowd of soldiers, students and civic leaders, is the first international partnership in Killeen’s history. Officials said the bond was a natural one: thousands of Puerto Rican soldiers have passed through Fort Hood, and many have made Killeen home." },
        { t: "q", x: "“Every family at this post knows someone from the island, or has been stationed there. This just puts a name to a friendship that already existed.”", by: "— Killeen city official, at the signing" },
        { t: "p", x: "Under the sister-city framework, the two governments plan student exchanges, joint cultural festivals and trade introductions for small businesses. Organizers pointed to Killeen’s large and growing Puerto Rican community — a population shaped by decades of military assignments — as the engine that will keep the relationship alive long after the proclamations are framed and hung." },
        { t: "h", x: "A friendship built at the post" },
        { t: "p", x: "Fort Hood, one of the largest military installations in the world, has long drawn soldiers from every U.S. state and territory. Puerto Rico, with one of the highest rates of military service per capita, has sent generations of soldiers through its gates. For many of those families, Killeen became the stateside hometown between deployments." },
        { t: "p", x: "Supporters of the agreement said the formal tie would help newly arrived families find community faster, and give Killeen students a cultural and academic link to the Caribbean. San Juan, founded in 1521, offers a counterpoint of history and tourism to a young Texas city still defining itself." },
        { t: "h", x: "What happens next" },
        { t: "p", x: "City staff said the first exchanges could begin within the year, starting with high school and community-college programs. A joint heritage celebration is under discussion for the following fall." },
        { t: "p", x: "For a city whose identity has always been wrapped up in the comings and goings of the Army, leaders framed the partnership as something that would outlast any single deployment cycle — a permanent thread between two places that the soldiers had already tied together." },
      ],
    },

    /* ===== Fort Hood widow (high-equity legacy) ===== */
    {
      id: "fort-hood-widow-remembers",
      section: "news",
      kicker: "Fort Hood",
      title: "A Widow Remembers, One Year After the Fort Hood Attack",
      dek: "As the post marks a somber anniversary, a young mother talks about the husband she lost, the daughter who never met him, and a community still healing.",
      hero: G.memorial,
      heroCap: "A memorial wreath rests at the Fort Hood remembrance site on the anniversary of the attack.",
      author: "Marcus Webb",
      role: "Staff Writer",
      date: "November 5, 2010",
      readMin: 5,
      tags: ["Fort Hood", "Killeen", "Remembrance"],
      body: [
        { t: "p", x: "FORT HOOD — A year is a long time and no time at all, she said, standing near the field where it happened. The flowers people leave have changed with the seasons. The hole has not." },
        { t: "p", x: "On the anniversary of the deadliest attack ever to take place on a domestic military base, the families of the fallen gathered with soldiers and strangers to remember thirteen lives. Among them was a young widow holding the hand of a daughter who was born after her father was gone." },
        { t: "q", x: "“I tell her who he was. I show her the pictures. I want her to know he was the kind of man who ran toward people who needed help.”", by: "— The soldier’s widow" },
        { t: "p", x: "The ceremony was quiet and deliberate. Names were read. A bell rang. Senior officers spoke of resilience, but the families spoke of breakfast tables and inside jokes and the ordinary routines that grief had rearranged." },
        { t: "h", x: "A community that absorbed the blow" },
        { t: "p", x: "Killeen and the surrounding towns have lived in Fort Hood’s rhythm for generations — the deployments, the homecomings, the missing seats at the table. The attack tested that bond in a way deployment never had, residents said, because the danger had come home." },
        { t: "p", x: "In the year since, support groups have multiplied, and neighbors have learned the names of families they once only nodded to. The widow said the casseroles eventually stopped, as they do, but the smaller kindnesses did not." },
        { t: "p", x: "She plans to stay in Central Texas, she said. It is where her husband’s friends are, where her daughter’s godparents wear the same uniform he did. It is, for better and worse, home." },
      ],
    },

    /* ===== Matt Baker trial (high-equity legacy) ===== */
    {
      id: "matt-baker-appeal",
      section: "crime",
      kicker: "Crime & Courts",
      title: "The Long Road of the Matt Baker Case Returns to Court",
      dek: "Years after a former Waco-area pastor was convicted in his wife’s death, a new defense motion revives one of Central Texas’s most closely watched cases.",
      hero: G.court,
      heroCap: "The McLennan County courthouse, where the Baker case drew national attention.",
      author: "Ellen Frost",
      role: "Courts Reporter",
      date: "Updated June 9, 2026",
      readMin: 5,
      tags: ["Waco", "McLennan County", "Courts"],
      body: [
        { t: "p", x: "WACO — It was the case that filled the gallery for weeks: a former pastor, a wife found dead in what was first ruled a suicide, and a family that refused to let the question go. This week, the Matt Baker case returned to a McLennan County courtroom, where his defense filed a fresh motion built around evidence it says deserves another look." },
        { t: "p", x: "The 2010 trial ended in a murder conviction and a 65-year sentence, capping a years-long fight led largely by the victim’s family, whose persistence kept investigators on a case that had nearly gone cold." },
        { t: "q", x: "“We waited a long time for a courtroom to take this seriously the first time. We can wait again.”", by: "— A member of the victim’s family" },
        { t: "h", x: "How the case became a landmark" },
        { t: "p", x: "What made the case extraordinary was not only the verdict but the path to it — a death initially recorded as a suicide, reopened after relatives pressed for answers and a civil suit pried loose details a criminal file had not. It became a fixture of true-crime coverage and a touchstone in Central Texas for the limits, and the reach, of a family’s determination." },
        { t: "h", x: "What the new motion argues" },
        { t: "p", x: "The defense filing seeks review of forensic material and asks the court to weigh standards that have shifted in the years since the conviction. Prosecutors signaled they would oppose it. A hearing date has not been set." },
        { t: "p", x: "For a region that watched the original trial gavel to gavel, the reopening is a reminder that some cases never fully close — they only wait for the next motion, the next hearing, the next morning the courthouse doors open." },
      ],
    },

    /* ===== Brittney Griner / Baylor (high-equity legacy) ===== */
    {
      id: "griner-freshman-of-the-year",
      section: "sports",
      kicker: "Baylor",
      title: "Griner Named National Freshman of the Year as Baylor Surges",
      dek: "The shot-blocking phenom’s debut season rewrites the record book and puts Central Texas women’s basketball squarely on the national stage.",
      hero: G.hoops,
      heroCap: "The Lady Bears celebrate at the Ferrell Center during a banner freshman campaign.",
      author: "Tre Coleman",
      role: "Sports Writer",
      date: "April 2, 2010",
      readMin: 4,
      tags: ["Baylor", "Lady Bears", "Basketball"],
      body: [
        { t: "p", x: "WACO — They came to the Ferrell Center to watch something they had never seen, and most nights they did. Baylor’s freshman center was named the national Freshman of the Year this week after a season that turned a strong program into a national headline." },
        { t: "p", x: "The numbers were the kind that made opposing coaches rewrite game plans — a shot-blocking total that rewrote the freshman record, a scoring presence that bent defenses around her, and a dunk that traveled far beyond Central Texas on highlight reels." },
        { t: "q", x: "“You build a season around a player like that maybe once in a coaching life. We know what we have.”", by: "— A Lady Bears coach" },
        { t: "h", x: "A program on the rise" },
        { t: "p", x: "The honor capped a season in which the Lady Bears climbed the national rankings and drew sellout energy to home games. For a region that lives and dies with Baylor athletics, the women’s team had become must-watch television." },
        { t: "p", x: "Teammates credited the freshman’s work ethic as much as her wingspan, and coaches were careful to spread praise across a roster that had bought into a defense-first identity. But there was no mistaking the gravity at the center of it." },
        { t: "p", x: "What it meant for Central Texas was simple: the cameras were here now, and they were not leaving. The freshman season was a beginning, and everyone in the building seemed to know it." },
      ],
    },

    /* ===== Mama cat / dachshunds (viral community legacy) ===== */
    {
      id: "mama-cat-dachshund-puppies",
      section: "community",
      kicker: "Community",
      title: "A Mama Cat Adopts a Litter of Orphaned Dachshund Puppies",
      dek: "At a Central Texas shelter, a nursing cat took in three motherless puppies — and a feel-good story raced around the internet.",
      hero: G.cats,
      heroCap: "A nursing cat curls around three orphaned dachshund puppies at the shelter.",
      author: "Sofia Marsh",
      role: "Community Reporter",
      date: "July 18, 2011",
      readMin: 3,
      tags: ["Temple", "Animals", "Feel-Good"],
      body: [
        { t: "p", x: "TEMPLE — The puppies needed a mother. The cat, it turned out, had room for three more. What happened next at a Central Texas animal shelter became the kind of story the internet was invented to share." },
        { t: "p", x: "When a litter of dachshund puppies arrived without a mother, shelter staff worried about round-the-clock bottle feeding. Then a nursing cat — already caring for her own kittens — wandered over, sniffed the newcomers, and simply made space." },
        { t: "q", x: "“She didn’t hesitate. She just decided they were hers, and that was the end of the discussion.”", by: "— A shelter volunteer" },
        { t: "p", x: "Within days, photos of the unlikely family had spread well beyond Bell County. The shelter said the attention brought a wave of adoption interest — and a reminder, staff said, that the small stories are sometimes the ones that travel farthest." },
        { t: "p", x: "All three puppies thrived under their adoptive mother’s watch. By summer’s end, the shelter said, every one had found a home." },
      ],
    },

    /* ===== CURRENT FEED ===== */
    {
      id: "fort-cavazos-barracks",
      section: "news",
      kicker: "Fort Cavazos",
      title: "Inside the $1.2 Billion Plan to Rebuild the Fort Cavazos Barracks",
      dek: "After two years of mold complaints and a damning Army audit, the post breaks ground on the largest soldier-housing overhaul in its history — and families say they’ll believe it when they see it.",
      hero: G.army,
      heroCap: "Crews begin demolition on a barracks block where mold complaints dated to 2023.",
      author: "Marcus Webb",
      role: "Staff Writer",
      date: "Updated 41 min ago",
      readMin: 6,
      tags: ["Fort Cavazos", "Killeen", "Military"],
      lead: true,
      body: [
        { t: "p", x: "FORT CAVAZOS — For two years the complaints piled up faster than the work orders — black mold behind the lockers, windows that wouldn’t seal, showers that ran cold by 6 a.m. On Monday, with a line of yellow excavators idling behind him, the garrison commander finally answered them." },
        { t: "p", x: "The plan calls for demolishing eleven aging barracks and replacing them with modern, climate-controlled buildings over four years — the single largest investment in soldier housing the installation has ever seen." },
        { t: "q", x: "“We’ll believe it when we’re sleeping in it.”", by: "— A soldier’s spouse whose husband deploys this fall" },
        { t: "h", x: "Years of complaints" },
        { t: "p", x: "An Army audit released last year found persistent moisture and ventilation problems across several barracks, some dating to construction decades ago. Soldiers had documented the conditions in photos that circulated widely, adding pressure on commanders to act." },
        { t: "p", x: "Officials said the new buildings would meet current standards for air quality and energy efficiency, and that displaced soldiers would be housed off-post during construction." },
        { t: "h", x: "An economic anchor" },
        { t: "p", x: "The project also lands as a major construction contract for a regional economy that runs on the post, from Killeen to Copperas Cove. Local leaders welcomed the spending even as families pressed for a timeline they could trust." },
        { t: "p", x: "Groundbreaking, the commander said, was the easy part. The hard part — finishing on schedule — starts now." },
      ],
    },
    {
      id: "silos-district-growth",
      section: "news",
      kicker: "Waco",
      title: "The Silos District Keeps Growing. Who Is the New Waco For?",
      dek: "Property values near the old grain silos have tripled since 2018. As two more blocks break ground, longtime residents are asking hard questions.",
      hero: G.silos,
      heroCap: "Visitors stream past the silos in downtown Waco on a Saturday afternoon.",
      author: "Dana Ruiz",
      role: "Staff Writer",
      date: "8 hours ago",
      readMin: 5,
      tags: ["Waco", "Development", "Downtown"],
      body: [
        { t: "p", x: "WACO — On a good Saturday, the sidewalks around the silos look less like downtown Waco and more like a state fair — strollers, sample cups, license plates from three states over. For the city, it has been a windfall. For the people who lived here first, it is more complicated." },
        { t: "p", x: "Property values within a few blocks of the silos have roughly tripled since 2018, city records show. Two more blocks broke ground this spring, and the question residents keep asking at council meetings is a simple one: who is all of this for?" },
        { t: "h", x: "A boom with a footprint" },
        { t: "p", x: "Developers point to jobs and tax revenue. Longtime residents point to rents. Both are right, which is what makes the debate so hard to settle." },
        { t: "p", x: "City planners said they were studying tools to keep longtime residents in place, but acknowledged the market was moving faster than policy." },
      ],
    },
    {
      id: "loop-172-expansion",
      section: "politics",
      kicker: "Killeen",
      title: "Killeen Council Greenlights Long-Delayed Loop 172 Expansion",
      dek: "After years of studies and stalled funding, the city approves a widening project drivers have demanded since the last boom.",
      hero: G.road,
      heroCap: "Traffic backs up along Loop 172 during a weekday afternoon commute.",
      author: "P. Okafor",
      role: "City Hall Reporter",
      date: "1 hour ago",
      readMin: 3,
      tags: ["Killeen", "Transportation", "City Council"],
      body: [
        { t: "p", x: "KILLEEN — The city council voted Tuesday to move forward with a long-delayed expansion of Loop 172, ending years of studies, public meetings and stalled funding that had frustrated commuters." },
        { t: "p", x: "The project will add lanes to one of the city’s most congested corridors, a route that carries thousands of Fort Cavazos workers each day. Construction is expected to begin next year." },
        { t: "p", x: "Council members framed the vote as overdue, while cautioning residents to brace for the disruption that comes with any major road job." },
      ],
    },
    {
      id: "temple-isd-four-day",
      section: "news",
      kicker: "Education",
      title: "Temple ISD Approves Four-Day Week Pilot for 2026–27",
      dek: "Trustees voted 5–2 to test a compressed calendar next fall, joining a growing number of Texas districts.",
      hero: G.school,
      heroCap: "Students leave a Temple ISD campus at the end of the school day.",
      author: "P. Okafor",
      role: "Education Reporter",
      date: "3 hours ago",
      readMin: 3,
      tags: ["Temple", "Education", "Schools"],
      body: [
        { t: "p", x: "TEMPLE — Temple ISD trustees voted 5–2 this week to pilot a four-day school week beginning in fall 2026, joining a growing roster of Texas districts experimenting with the compressed calendar as a tool for recruiting and keeping teachers." },
        { t: "p", x: "Supporters cited staffing pressures and survey data showing strong interest among families. Opponents raised concerns about child care and instructional time." },
        { t: "p", x: "The district said it would track attendance and test scores closely before deciding whether to make the change permanent." },
      ],
    },
    {
      id: "belton-lake-reopens",
      section: "news",
      kicker: "Bell County",
      title: "Belton Lake Reopens Boat Ramps After Months of Drought Closures",
      dek: "Rising water levels bring relief to a summer recreation economy that runs on the lake.",
      hero: G.lake,
      heroCap: "Boaters return to Belton Lake as water levels recover.",
      author: "Sofia Marsh",
      role: "Staff Writer",
      date: "2 hours ago",
      readMin: 2,
      tags: ["Belton", "Bell County", "Weather"],
      body: [
        { t: "p", x: "BELTON — Several boat ramps at Belton Lake reopened this week after months of drought-driven closures, a welcome sign for a summer recreation economy that depends on the water." },
        { t: "p", x: "Recent rains lifted levels enough to make the ramps usable again, officials said, though they cautioned that conditions could shift quickly if the dry pattern returns." },
      ],
    },
    {
      id: "heat-advisory",
      section: "weather",
      kicker: "Weather",
      title: "Heat Advisory Extended Through Friday Across the Region",
      dek: "Forecasters warn of dangerous afternoon highs from Waco to Killeen; cooling centers are open.",
      hero: G.radar,
      heroCap: "Regional radar shows clear skies and building heat across Central Texas.",
      author: "Weather Desk",
      role: "",
      date: "5 hours ago",
      readMin: 2,
      tags: ["Weather", "Heat"],
      body: [
        { t: "p", x: "CENTRAL TEXAS — Forecasters have extended a heat advisory through Friday, with afternoon highs expected to climb into the upper 90s and triple digits from Waco to Killeen." },
        { t: "p", x: "Officials urged residents to limit outdoor activity during peak hours, check on elderly neighbors, and never leave children or pets in parked cars. Cooling centers are open in several cities." },
      ],
    },
    {
      id: "baylor-recruit",
      section: "sports",
      kicker: "Sports",
      title: "Baylor Lands Five-Star Recruit as Bears Eye Another Deep Run",
      dek: "The commitment caps a strong recruiting cycle and raises expectations in Waco.",
      hero: G.hoops,
      heroCap: "A packed Ferrell Center during a marquee Baylor home game.",
      author: "Tre Coleman",
      role: "Sports Writer",
      date: "4 hours ago",
      readMin: 3,
      tags: ["Baylor", "Recruiting"],
      body: [
        { t: "p", x: "WACO — Baylor secured a commitment from one of the nation’s top recruits this week, a signing that caps a strong cycle and stokes expectations for another deep postseason run." },
        { t: "p", x: "Coaches praised the recruit’s versatility and said the class fit a clear identity. For a fan base accustomed to contending, the bar was set accordingly." },
      ],
    },
  ];

  const byId = (id) => ARTICLES.find((a) => a.id === id);
  const bySection = (slug) => ARTICLES.filter((a) => a.section === slug);

  return { SECTIONS, ARTICLES, byId, bySection, G };
})();
